apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "maxscale-helm.fullname" . }}-config
  labels:
    {{- include "maxscale-helm.labels" . | nindent 4 }}
data:
{{- if .Values.maxscaleConfiguration }}
  maxscale.cnf: |
{{ .Values.maxscaleConfiguration | indent 4 }}
{{- end }}
